# Generated by Django 5.1.3 on 2025-11-24 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0007_workshift_created_at_workshift_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao', null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(db_column='da_xoa', default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat', null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao', null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(db_column='da_xoa', default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat', null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao', null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(db_column='da_xoa', default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat', null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao', null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(db_column='da_xoa', default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat', null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao', null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, db_column='du_lieu_json', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_column='da_xoa', default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_column='da_doc', default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(db_column='noi_dung'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], db_column='trang_thai', default='unread', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(db_column='loai_thong_bao', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat', null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(db_column='ma_nguoi_dung', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao', null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(db_column='da_xoa', default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat', null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao', null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='is_deleted',
            field=models.BooleanField(db_column='da_xoa', default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat', null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao', null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_column='da_xoa', default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat', null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao', null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='is_deleted',
            field=models.BooleanField(db_column='da_xoa', default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat', null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao', null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='is_deleted',
            field=models.BooleanField(db_column='da_xoa', default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat', null=True, verbose_name='updated_at'),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='thong_bao',
        ),
    ]
