# Generated by Django 5.1.3 on 2025-11-24 22:00

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0008_alter_comment_created_at_alter_comment_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellingproduct',
            name='product',
            field=models.ForeignKey(db_column='ma_san_pham', on_delete=django.db.models.deletion.CASCADE, to='web_01.product'),
        ),
        migrations.AlterField(
            model_name='bestsellingproduct',
            name='report_date',
            field=models.DateTimeField(db_column='ngay_bao_cao'),
        ),
        migrations.AlterField(
            model_name='bestsellingproduct',
            name='sold_quantity',
            field=models.IntegerField(db_column='so_luong_da_ban'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(db_column='ma_khach_hang', on_delete=django.db.models.deletion.CASCADE, to='web_01.customer'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(db_column='ma_gio_hang', on_delete=django.db.models.deletion.CASCADE, to='web_01.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(db_column='ma_san_pham', on_delete=django.db.models.deletion.CASCADE, to='web_01.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(db_column='so_luong', default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, db_column='mo_ta', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='ten_loai_san_pham', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='cha_loai_san_pham', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_01.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Ngưng hoạt động')], db_column='trang_thai', default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='bot_reply',
            field=models.TextField(db_column='tin_nhan_bot'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='thoi_gian_tao'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user_message',
            field=models.TextField(db_column='tin_nhan_nguoi_dung'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, db_column='noi_dung', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(db_column='ma_san_pham', on_delete=django.db.models.deletion.CASCADE, to='web_01.product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_column='ma_nguoi_dung', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(db_column='diem_tich_luy'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, db_column='ma_nguoi_dung', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avartar_url',
            field=cloudinary.models.CloudinaryField(blank=True, db_column='anh_dai_dien', max_length=255, null=True, verbose_name='avartar_url'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('chef', 'Chef')], db_column='vai_tro', default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(db_column='luong'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(db_column='ma_nguoi_dung', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_column='ten_nguyen_lieu', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_in_stock',
            field=models.IntegerField(db_column='so_luong_ton', default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('g', 'Gram'), ('ml', 'Milliliter'), ('chai', 'Chai'), ('gói', 'Gói'), ('hộp', 'Hộp'), ('lon', 'Lon'), ('cai', 'Cái'), ('lang', 'Lạng'), ('trai', 'Trái'), ('hop', 'Hộp'), ('o', 'Ổ'), ('cu', 'Củ'), ('lit', 'Lít'), ('ml', 'Ml'), ('chai', 'Chai'), ('quả', 'Quả')], db_column='don_vi_tinh', max_length=5),
        ),
        migrations.AlterField(
            model_name='ingredientproduct',
            name='ingredient',
            field=models.ForeignKey(db_column='ma_nguyen_lieu', on_delete=django.db.models.deletion.CASCADE, to='web_01.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientproduct',
            name='product',
            field=models.ForeignKey(db_column='ma_san_pham', on_delete=django.db.models.deletion.CASCADE, to='web_01.product'),
        ),
        migrations.AlterField(
            model_name='ingredientproduct',
            name='quantity_required',
            field=models.IntegerField(db_column='so_luong_can'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='change',
            field=models.IntegerField(db_column='so_luong_thay_doi'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='ingredient',
            field=models.ForeignKey(db_column='ma_nguyen_lieu', on_delete=django.db.models.deletion.CASCADE, to='web_01.ingredient'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, db_column='thoi_gian_cap_nhat'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='note',
            field=models.TextField(blank=True, db_column='ghi_chu', null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='stock_after',
            field=models.IntegerField(blank=True, db_column='so_luong_sau', null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='stock_before',
            field=models.IntegerField(blank=True, db_column='so_luong_truoc', null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='type',
            field=models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho'), ('sell', 'Bán hàng'), ('adjustment', 'Điều chỉnh')], db_column='loai_thay_doi', max_length=15),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='ma_nguoi_dung', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(db_column='giam_gia', default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản'), ('momo', 'Momo')], db_column='phuong_thuc_thanh_toan', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(db_column='ma_phien_phuc_vu', on_delete=django.db.models.deletion.CASCADE, to='web_01.session'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.IntegerField(db_column='tong_tien', default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(db_column='giam_gia', default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(db_column='ma_hoa_don', on_delete=django.db.models.deletion.CASCADE, to='web_01.invoice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ'), ('in_progress', 'Đang làm'), ('completed', 'Hoàn thành'), ('cancelled', 'Hủy')], db_column='trang_thai', default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(db_column='tong_tien', default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(db_column='ma_don_hang', on_delete=django.db.models.deletion.CASCADE, to='web_01.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.IntegerField(db_column='gia'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(db_column='ma_san_pham', on_delete=django.db.models.deletion.CASCADE, to='web_01.product'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(db_column='so_luong'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ'), ('in_progress', 'Đang làm'), ('completed', 'Hoàn thành'), ('cancelled', 'Hủy')], db_column='trang_thai', default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total',
            field=models.IntegerField(db_column='thanh_tien'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='ma_loai_san_pham', on_delete=django.db.models.deletion.CASCADE, to='web_01.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_column='mo_ta', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, db_column='hinh_anh', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='ten_san_pham', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(db_column='gia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Ngưng hoạt động')], db_column='trang_thai', default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(db_column='ma_san_pham', on_delete=django.db.models.deletion.CASCADE, to='web_01.product'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], db_column='diem_so', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(db_column='ma_nguoi_dung', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='customer',
            field=models.ForeignKey(db_column='ma_khach_hang', on_delete=django.db.models.deletion.CASCADE, to='web_01.customer'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ended_at',
            field=models.DateTimeField(blank=True, db_column='thoi_gian_ket_thuc', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_column='thoi_gian_bat_dau'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], db_column='trang_thai', default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='table',
            field=models.ForeignKey(db_column='ma_ban', on_delete=django.db.models.deletion.CASCADE, to='web_01.table'),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao'),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='date',
            field=models.DateField(db_column='ngay_dang_ky'),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='employee',
            field=models.ForeignKey(db_column='ma_nhan_vien', on_delete=django.db.models.deletion.CASCADE, related_name='shift_registrations', to='web_01.employee'),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='is_off',
            field=models.BooleanField(db_column='xin_nghi', default=False),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='reason',
            field=models.TextField(blank=True, db_column='ly_do', null=True),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Sáng'), ('afternoon', 'Chiều'), ('evening', 'Tối'), ('allday', 'Cả Ngày')], db_column='loai_ca', max_length=10),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_column='trang_thai', default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(db_column='suc_chua', default=4),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_deleted',
            field=models.BooleanField(db_column='da_xoa', default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='qr_image',
            field=cloudinary.models.CloudinaryField(db_column='anh_qr', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Trống'), ('occupied', 'Sử dụng'), ('reserved', 'Đã đặt')], db_column='trang_thai', default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(db_column='so_ban', unique=True),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='date',
            field=models.DateField(db_column='ngay_dat'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='hour',
            field=models.TimeField(db_column='gio_dat'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='many_person',
            field=models.IntegerField(db_column='so_nguoi'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='name',
            field=models.CharField(db_column='ten_khach_hang', max_length=100),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='phone_number',
            field=models.CharField(db_column='so_dien_thoai', max_length=15),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Đã hoàn thành')], db_column='trang_thai', default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='table',
            field=models.ForeignKey(blank=True, db_column='ma_ban', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='web_01.table'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='date',
            field=models.DateField(db_column='ngay'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='employee',
            field=models.ForeignKey(db_column='ma_nhan_vien', on_delete=django.db.models.deletion.CASCADE, related_name='workshifts', to='web_01.employee'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='notes',
            field=models.TextField(blank=True, db_column='ghi_chu', null=True),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Sáng'), ('afternoon', 'Chiều'), ('evening', 'Tối'), ('allday', 'Cả Ngày')], db_column='loai_ca', max_length=10),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='time_end',
            field=models.DateTimeField(blank=True, db_column='thoi_gian_ket_thuc', null=True),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='time_start',
            field=models.DateTimeField(blank=True, db_column='thoi_gian_bat_dau', null=True),
        ),
        migrations.AlterModelTable(
            name='bestsellingproduct',
            table='sanpham_banchay',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='giohang',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='giohang_chitiet',
        ),
        migrations.AlterModelTable(
            name='chathistory',
            table='lichsu_tinnhan',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='binhluan',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='khachhang',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='nhanvien',
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='nguyenlieu',
        ),
        migrations.AlterModelTable(
            name='ingredientproduct',
            table='congthuc_sanpham',
        ),
        migrations.AlterModelTable(
            name='inventorylog',
            table='phieunhap_xuat',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='hoadon',
        ),
        migrations.AlterModelTable(
            name='order',
            table='donhang',
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='donhang_chitiet',
        ),
        migrations.AlterModelTable(
            name='product',
            table='sanpham',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='danhgia',
        ),
        migrations.AlterModelTable(
            name='session',
            table='phienphucvu',
        ),
        migrations.AlterModelTable(
            name='shiftregistration',
            table='dangky_ca',
        ),
        migrations.AlterModelTable(
            name='table',
            table='ban_an',
        ),
        migrations.AlterModelTable(
            name='tablereservation',
            table='datban',
        ),
        migrations.AlterModelTable(
            name='workshift',
            table='phancong_ca',
        ),
    ]
