# Generated by Django 5.1.3 on 2025-11-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0009_alter_bestsellingproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='loai_san_pham',
        ),
    ]
