# Generated by Django 5.1.3 on 2025-12-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0010_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(db_column='so_ban', null=True, unique=True),
        ),
    ]
