# Generated by Django 5.1.3 on 2025-12-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0011_alter_table_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, db_column='ten', max_length=100, null=True),
        ),
    ]
