# Generated by Django 5.1.3 on 2025-12-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0012_employee_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=254, null=True, unique=True),
        ),
    ]
